# Generated by Django 5.2.6 on 2025-11-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key_id', models.SlugField(max_length=20, unique=True)),
                ('secret_access_key', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.executionorder')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.accesskey')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.method')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.name')),
            ],
        ),
        migrations.AddField(
            model_name='executionorder',
            name='service',
            field=models.ManyToManyField(through='aws.Closure', to='aws.service'),
        ),
        migrations.AddField(
            model_name='closure',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.service'),
        ),
        migrations.CreateModel(
            name='DefaultConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.service')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.valuetype')),
            ],
            options={
                'unique_together': {('key', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.closure')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.valuetype')),
            ],
            options={
                'unique_together': {('key', 'closure')},
            },
        ),
    ]
