# Generated by Django 5.2.6 on 2025-11-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(db_index=True, max_length=79)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.closure')),
                ('variable_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.valuetype')),
            ],
            options={
                'indexes': [models.Index(fields=['closure', 'variable_name'], name='aws_respons_closure_b23335_idx')],
                'unique_together': {('closure', 'variable_name')},
            },
        ),
    ]
