# Generated by Django 5.2.6 on 2025-11-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_responseconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='closure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.closure'),
        ),
    ]
