# Generated by Django 5.2.6 on 2025-11-25 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_alter_configuration_closure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultConfigurationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_set', to='aws.defaultconfiguration')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.defaultconfiguration')),
            ],
            options={
                'unique_together': {('name', 'configuration')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.configuration')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.packagename')),
            ],
            options={
                'unique_together': {('name', 'configuration')},
            },
        ),
    ]
