# Generated by Django 5.2.6 on 2025-11-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_packagename_defaultconfigurationpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconfigurationpackage',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.defaultconfiguration'),
        ),
        migrations.AlterField(
            model_name='defaultconfigurationpackage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws.packagename'),
        ),
    ]
