# Generated by Django 5.2.6 on 2025-11-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_alter_defaultconfigurationpackage_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseconfiguration',
            name='variable_type',
        ),
    ]
