# Generated by Django 5.2.6 on 2025-11-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_remove_responseconfiguration_variable_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseConfiguration',
        ),
    ]
