# Generated by Django 5.2.6 on 2025-11-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_delete_responseconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='closure',
            name='variable_name',
            field=models.CharField(blank=True, max_length=79, null=True),
        ),
    ]
